language: node_js

node_js:
  - "node"

os:
  - linux
  - osx

env:
  - CODE_VERSION=1.22.0 # Minimal Version
  - CODE_VERSION=* # Last Stable Version
  - CODE_VERSION=insiders # Insider Version

cache:
  directories:
    - "node_modules"

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3;
    fi

install:
  - node --version
  - npm --version
  - npm install

before_script:
  - npm run vscode:prepublish
  # Enable coverage for `extension.ts`
  - sed -i.bak 's/"\*"//g' package.json

script:
  - npm run lint
  - npm test --silent

after_script:
  - node_modules/.bin/coveralls < coverage/lcov.info